### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'corpus'

### ISSUE THREAD

**Issue by SeekPoint** [FanhuaandLuomu/BiLstm_CNN_CRF_CWS#3]
mldl@mldlUB1604:~/ub16_prj/BiLstm_CNN_CRF_CWS$ python3 embedding_model.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "embedding_model.py", line 20, in <module>
    sentences=MySentences([corpus_path+os.sep+fname for fname in os.listdir(corpus_path)])
FileNotFoundError: [Errno 2] No such file or directory: 'corpus'
mldl@mldlUB1604:~/ub16_prj/BiLstm_CNN_CRF_CWS$

**Comment by QLMX** [comment]
os.listdir需要绝对路径

**Comment by SeekPoint** [comment]
works
